### ISSUE TITLE
Add status icons for various conditions DCC's crits and fumbles generate

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/dcc#121]
E.g.

- Prone (Lots of Crits and Fumbles)
- Grip Disrupted (Fumble 3)
- Weapon Damaged (Fumble 4)
- Weapon Entangled in Armor (Fumble 6)
- Weapon Dropped (Fumble 7) / Disarmed (Crit I 0)
- Stumbling (Fumble 9)
- Armor Siezed (Fumble 10)
- Off Balance / Disoriented (Fumble 11)
- Turtled (Fumble 14)
- Kneecapped (Crit I 4) / Splintered Femur (Crit III 9)
- Stunned (Crit I 8)
- Blinded (Crit I 9) - usually by blood
- Retching (Crit I 12)
- Silenced (Crit I 17)
- Scarred (Crit II 2)
- Dazed (Crit II 6)
- Wet Fish Noises (Crit II 11) (Crit IV 9)
- Unconscious (Crit II 14)
- Eye Popped (Crit II 16) Shattered Face (Crit III 26)
- Pierced Lung (Crit II 17)
- Paralysis (Crit II 21)
- Battle Rage (Crit III 0)
- Nose Smashed (Crit III 5)
- Broken Ribs (Crit III 6)
- Deafened (Crit III 8)
- Internal Bleeding (Crit III 11)
- Dislocated Shoulder (Crit III 15)
- Hand Smashed (Crit III 16)
- Amnesia (Crit IV 18)
- Jellied Organs (Crit IV 21) Disembowelled (Crit IV 22) Skull Crushed (Crit IV 24+) - basically dieing in 1dx rounds
- Shortened (Crit V 16)
- Voids Bowels (Crit V 25)

**Comment by cyface** [comment]
There are so many of these and they are so very specific - I feel like we need some sort of other mechanic to show these - l don't think we would ever remember all of the icon to text mappings. 😂 

Maybe just a single "Crit Effect" status icon, and then a text box to type in the effect, or link to the crit result?

**Comment by mooped** [comment]
The list definitely needs to be cut down, I'll have a think about the essential variants.

**Comment by mooped** [comment]
Let's see if there's a way to override these at a system level so we don't disrupt existing functionality (like these icons showing in the combat tracker, and come up with a cut down list of the useful ones (plus a few generic Crit Status 1/2/3 icons) from FontAwesome to replace some of the less useful stock status icons with.
