### ISSUE TITLE
Add the image for a weapon (if there is one) next to the weapon where the D20 icon is right now

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#145]
![image](https://user-images.githubusercontent.com/7275595/109354218-770aaa00-784b-11eb-916c-6e574db8b113.png)

Would be nice to have the image for a weapon appear next to it.

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/115987944-3f9c4d80-a5af-11eb-8d72-691498fd1d56.png)

I've added this as part of the drag from sheet refactor, weapons and armor need something to drag, and I'd prefer not to make textboxes draggable since it messes with selecting text.

**Comment by mooped** [comment]
Released in v0.26.0
