### ISSUE TITLE
Differential Ability Score Changes - e.g. type "-3" on ability scores like you do with hp

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/dcc#148]
In addition to having 'max' values for each attribute, we should consider being able to type "-3" on ability scores like you do with hit points to do instant math on them, since scores move around so much during the game.

**Comment by mooped** [comment]
We can detect entries with a leading - or + in the actor sheet's _updateObject and apply the deltas. We already hook item updates here.

**Comment by cyface** [comment]
I built this locally and then decided I didn't like it, so I am going to close this one. :)
