### ISSUE TITLE
Add A Journal Entry for Release Notes and Dialog that Shows It Every Upgrade

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#166]
Add a release notes journal entry, maybe it could pop up after each upgrade?

**Comment by mooped** [comment]
Let's make this a chat card so it's unobtrusive and also visible to players. This can have buttons or links to open the relevant journals.

**Comment by mooped** [comment]
Query the system version on launch and compare to a hidden setting (similar but separate to dcc.systemMigrationVersion) to determine when to add this chat card.

**Comment by mooped** [comment]
Fixed on 0.28.0.
