### ISSUE TITLE
"Lost" Checkbox for Wizard Spells - Automation

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/dcc#172]
Ideally, if lost box is checked, prompt the player to spend a luck to cast the spell.

Really ideally, if a 'lost/fail' result comes up when casting, check this box automatically.

**Comment by mooped** [comment]
![wizard_miscast](https://user-images.githubusercontent.com/371357/125177715-08186700-e1d6-11eb-8743-d070d55d3eb0.gif)

We now pop up a message when a wizard fails to cast a spell (based on a threshold of 12 for the generic Spell Check button and the appropriate value for Spell Items). If casting through a spell with the Casting Mode set to 'wizard' the spell is marked as lot.

Needs a bit more work to make this optional. I've made issue #264 to track that additional task.
