### ISSUE TITLE
Equipment Tab - Deed Roll Formatting Cleanup

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/dcc#181]
The "Deed Roll" on the Equipment tab needs some formatting assistance.

Vertical align label and field, left-align it on top of the equipment sheet.

Add ring around value box.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/49695/110247908-c461d800-7f2b-11eb-929f-b0829595853d.png">

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/128641539-a236b793-d883-4c0b-9478-550ce7255194.png)

**Comment by mooped** [comment]
I wish either Foundry or Font-Awesome provided a black d4 icon!

Foundry only has a grey one. Font-Awesome's d4 is pro only (and a bit weird).
