### ISSUE TITLE
Prevent Editing Mercurial Magic on Items Directly

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/dcc#194]
Should only be editable once attached to a character (maybe don't even show the fields on the item if it's not on a character?)

**Comment by mooped** [comment]
This logic already exists and is exposed to the template to hide the mercurial magic roll item. It just needs to wrap the whole mercurial magic section of the form.

**Comment by mooped** [comment]
The main obstacle is the grid based layout doesn't handle missing fields well. Need to rework this.
