### ISSUE TITLE
Make it easy to increase or decrease Cleric Disapproval

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#201]
Something could make Disapproval less frustrating. Currently when you click into it to edit it, you increase it. Maybe if there were up/down arrows, or +/- on the sides of it.

**Comment by MichalKolesinski** [comment]
Maybe left/right mouse click would do?

**Comment by mooped** [comment]
Disapproval is now a dropdown to make this easier.

![image](https://user-images.githubusercontent.com/371357/130363742-127e2b1e-b01a-44de-9d8b-e5a5bd557ef8.png)
