### ISSUE TITLE
Show the Mercurial effect on spell result draw

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#208]
It would be nice to see the Mercurial effect of a spell in the chat window on spell rolls - maybe it could be a per spell option, so people can disable it if they think it fills up their chat window.

**Comment by mooped** [comment]
Maybe also add a pre/post mode, so the mercurial can interrupt the spell check process, to give an opportunity to handle effects that alter the spell check roll.

**Comment by mummson** [comment]
Is there any ETA for this?

**Comment by gabecook** [comment]
New judge. I was just testing spell casting and was looking for the mecurial magic effect in the chat card and didn't see it. I ended up here after looking through the options. This would be very nice to have. As always, thanks for all of your work on this system!
