### ISSUE TITLE
Add Deed Die option for NPCs

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#227]
Similar to skill and spell tabs, it would be nice if NPCs could have an option to roll their attack bonus. This is important for Lankhmar NPCs.

**Comment by mooped** [comment]
Implemented for 0.32.0.

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/141649348-876781d1-7a6f-46e4-a3fd-01ec2edc67f5.png)
