### ISSUE TITLE
.8.2. issues mega issue

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#232]
Trying to open a PC from the actors menu:

Uncaught (in promise) TypeError: sheetData.data.config is undefined
_prepareItems http://localhost:30000/systems/dcc/module/actor-sheet.js:127
getData http://localhost:30000/systems/dcc/module/actor-sheet.js:92
_render http://localhost:30000/scripts/foundry.js:2030
_render http://localhost:30000/scripts/foundry.js:2717
render http://localhost:30000/scripts/foundry.js:1992
render http://localhost:30000/scripts/foundry.js:3179
_onClickEntityName http://localhost:30000/scripts/foundry.js:23134
_onClickEntityName http://localhost:30000/scripts/foundry.js:31463
jQuery 2
actor-sheet.js:127:9
ReferenceError: An error occurred while rendering DCCActorSheet 62: ENTITY_PERMISSIONS is not defined
_getHeaderButtons http://localhost:30000/systems/dcc/module/actor-sheet.js:34
_renderOuter http://localhost:30000/scripts/foundry.js:2159
_render http://localhost:30000/scripts/foundry.js:2047

Unable to open NPC actorSheet

Foundry VTT | Rendering DCCActorSheet foundry.js:2021:15
You are referencing DocumentSheet#entity which has been deprecated in favor of DocumentSheet#document foundry.js:3220:12
You are using the Document#owner property which has been deprecated in favor of Document#isOwner and will be removed in 0.9.0 foundry.js:9604:13
You are referencing DocumentSheet#entity which has been deprecated in favor of DocumentSheet#document 5 foundry.js:3220:12
ReferenceError: An error occurred while rendering DCCActorSheet 63: ENTITY_PERMISSIONS is not defined
_getHeaderButtons http://localhost:30000/systems/dcc/module/actor-sheet.js:34
_renderOuter http://localhost:30000/scripts/foundry.js:2159
_render http://localhost:30000/scripts/foundry.js:2047
_render http://localhost:30000/scripts/foundry.js:2717
render http://localhost:30000/scripts/foundry.js:1992
render http://localhost:30000/scripts/foundry.js:3179
_onClickEntityName http://localhost:30000/scripts/foundry.js:23134
_onClickEntityName http://localhost:30000/scripts/foundry.js:31463
jQuery 2

Unable to create, import items
Uncaught (in promise) Error: this._cleanHTML is not a function
foundry.js:1246:46

**Comment by mooped** [comment]
These and more are fixed on feature_fvtt0.8.x.

Any new 0.8.x issues should be reported as separate bugs now the initial raft of fixes are in.
