### ISSUE TITLE
Line-Height in Notes field is too short for roll expressions

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/dcc#239]
If we can make the roll expressions shorter, that's probably the best solution.  Otherwise we'll need to increase the line-height to fit them if they appear.

![image](https://user-images.githubusercontent.com/49695/119264485-a574f880-bba0-11eb-8a95-f6a863e28a4a.png)

**Comment by mooped** [comment]
I've had a play and picked some hopefully reasonable values. The defaults seem to end up tiny, we were using a relative font size of 1.2rems and not adjusting the line height. They're now both specified absolutely in px.

![image](https://user-images.githubusercontent.com/371357/120199971-b74b4100-c21b-11eb-821b-627c03d06614.png)

**Comment by cyface** [comment]
That looks better. I think we can go with that.
