### ISSUE TITLE
LootSheet Support

### ISSUE THREAD

**Issue by justinthejaguar** [foundryvtt-dcc/dcc#244]
Would it be possible to include support for Lootsheets in DCC? 

The three functionalities that seem applicable would be setting up a shop for players so that they could make any purchases during the session without the Judge needing to pull the items from the compendium/items tab every time for them.

This would also be useful for looting a chest, so that the players could get a good look at what the item does and determine on their own who should get it.

The third functionality would be to allow the players to split the loot or value of the loot on one button in the loot sheet.

For reference, there is a module that does this for D&D 5E called LootSheetNPC5e:
https://github.com/jopeek/fvtt-loot-sheet-npc-5e

**Comment by TylerKostuch** [comment]
I actually forked Loot Sheet and started working on it. From what I remember, it was displaying correctly and I just had to hookup the interactions.

https://github.com/TylerKostuch/fvtt-loot-sheet-npc-5e/tree/dcc-refactor

**Comment by justinthejaguar** [comment]
Just awesome that someone is working on it. Thanks!

**Comment by TylerKostuch** [comment]
@justinthejaguar, just thought you should know that I've picked development up again.

The "Loot" type is 90% working, coinage being the big thing left. "Merchant" sheets haven't been touched yet. I'll let you know when I get something working, as it would be nice to have someone else testing it as well if you're so inclined.

![image](https://user-images.githubusercontent.com/32139518/125567658-f13047a0-97b5-4914-af02-f3a43320e7eb.png)

**Comment by mooped** [comment]
[Item Piles](https://github.com/fantasycalendar/FoundryVTT-ItemPiles) now provides this functionality.
