### ISSUE TITLE
Actor Portraits should maintain aspect ratio

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#251]
Actor portraits should maintain their aspect ratio instead of getting squashed

![image](https://user-images.githubusercontent.com/7275595/122411119-7f016d80-cf52-11eb-925b-19d9be95f3d3.png)

**Comment by mooped** [comment]
Fixed on dev-v0.29.0

**Comment by mooped** [comment]
The fix is not working correctly so this needs rework.

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/123550007-49832e00-d763-11eb-8ca4-2aa4d34cc96a.png)

Now fixed correctly.
