### ISSUE TITLE
Cleric cannot select Disapproval Table

### ISSUE THREAD

**Issue by TylerKostuch** [foundryvtt-dcc/dcc#253]
In prior versions, the Disapproval Tables Compendium would allow Clerics to select from the roll tables within that Compendium.  In version 0.28.0, only one table appears in the dropdown.

[Screenshot ](https://i.imgur.com/l16r0yJ.png) to illustrate the issue.

# Reproducing the Issue

### Example

[Download the example FoundryVTT world](https://drive.google.com/file/d/11PBZbliTrqum4HwdDZUhRakLD3Pxtoq_/view?usp=sharing)

1. Extract the world into the appropriate FoundryVTT `data/worlds/` directory.
2. Notice that the `Disapprovals` Compendium contains two roll tables (Disapproval A & Disapproval B)
3. Notice the Game Settings has the Disapproval Tables Compendium set correctly
4. Open the Foo character and inspect the Cleric tab, notice that the cleric cannot change the disapproval table.

### Steps taken

1. Create a new FoundryVTT world with the DCC game system (v 0.28.0)
2. Create a new Compendium (Roll Tables) 
3. Go to Configure Game Settings and specify that newly created compendium item for the "Disapproval Tables Compendium"
4. Create two roll tables and add them to the newly created Compendium.
5. Refresh FoundryVTT with F5
6. Create a new character and change the sheet to Cleric
7. Go to the Cleric tab, and notice that you cannot select the disapproval table.

**Comment by TylerKostuch** [comment]
Digging into this a bit, and it appears that the `config.disapporvalTables` ([used here](https://github.com/foundryvtt-dcc/dcc/blob/b9e89077c55c5436e17398fa00361bae4c2ca80b/templates/actor-sheet-cleric.html#L75)) has the following:

![image](https://user-images.githubusercontent.com/32139518/123697756-e527a380-d822-11eb-896c-af398c20a81e.png)

**Comment by mooped** [comment]
Thanks for spotting this and suggestiing a fix.

I think the original intention was that the table ID would be used as the value for the dropdown, but we ended up using the packname and table name since this can be directly applied when looking up the table.

I've merged your fix to our dev branch, so hopefully it will be in a release soon, and added you to the list of contributors.
