### ISSUE TITLE
Rolling initiative from Character Sheet does not work/from CT always roll d20

### ISSUE THREAD

**Issue by radoslawg** [foundryvtt-dcc/dcc#256]
Foundry VTT version 0.8.8 . Tested without any mods.

After adding token to CT, rolling Initiative from character sheet rolls it in the chat correctly but does not set value in Combat Tracker.
Using "Roll Initiative" function in Combat Tracker ignores Initiative die from character sheet and always rolls 1d20 + correct modifier

**Comment by mooped** [comment]
A tweaked version of this commit is on a branch waiting to be merged to dev. Thanks!

**Comment by mooped** [comment]
Fixed on dev-v0.29.0
