### ISSUE TITLE
Fumble die not working without a 1 in front of d

### ISSUE THREAD

**Issue by petepeg** [foundryvtt-dcc/dcc#261]
The compendium has all the fumble die on armor listed as d12, d16, etc. But it without a 1 in front it rolls a d4 on a fumble.

**Comment by mooped** [comment]
I've submitted a bug on Foundry's GitLab as this is down to some inconsistencies in how their Roll parser behaves.

See https://gitlab.com/foundrynet/foundryvtt/-/issues/5599 for details.
