### ISSUE TITLE
unchecking equipped Armor won't allow you to check it again.

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#262]
When you unequip armor, trying to equip it again doesn't work. It just unchecks quickly.

Dragging the armor off your sheet to your items folder, deleting the armor on your sheet, then dragging it back onto your sheet seems to work around the issue. You can check/uncheck then once.

**Comment by mooped** [comment]
Caused by a race between item updates and sheet updates.

**Comment by radoslawg** [comment]
Ha ha ha.. I just encounter this bug.. before looking here I tackled it in code. My fix is identical. :) But it took me an hour or two to trace. ;) Lesson learned.
