### ISSUE TITLE
Remove Roll dependency from Fumble Die calculation

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/dcc#263]
There is a workaround for #261 in, but it will break if v9 makes Roll.evaluate async only.

Hopefully https://gitlab.com/foundrynet/foundryvtt/-/issues/5599 will be resolved in a way that makes this a non-issue.

**Comment by mooped** [comment]
This works fine in release-9.220 (v9p1) - evaluate still implements both a sync and async path.

Still might be worth moving it to a regex based evaluation to avoid the need to worry about it in future versions.

**Comment by cyface** [comment]
I believe this is fixed and is no longer an issue.
