### ISSUE TITLE
Some enhancement ideas. 

### ISSUE THREAD

**Issue by mummson** [foundryvtt-dcc/dcc#270]
I've been using this module for quite some time (almost 1 year!) and there are somethings that I'd really like to see added/improved to the otherwise amazing implementation of DCC to foundry ;)

Here is my list in no particular order:
- Allow Ability modifiers to be overwritten/modified manually
- Have a "favorite" option for weapons, skills, spells and or items/equipment

- - And have them shown on the "Character" tab on the character sheet.

- If the PC has more than one action die additional die buttons in front of weapons for each action die
- Show Mercurial effect and manifestation when spells are rolled
- Don't show html tags in names of items/weapons 

- - Then you have the option to add flair to each item by adding html tags to names for bold, italic or what ever.

- Allow for some way to call on ability modifiers with rolls both for skills/weapons and custom rolls "+@AGILMOD" for agility or something along those lines.

**Comment by algnc** [comment]
> Allow Ability modifiers to be overwritten/modified manually

Do you mean change the ability modifier, aside from what the ability score should make the modifier? I.e. give someone with a 10 Personality a +3 modifier?

> Have a "favorite" option for weapons, skills, spells and or items/equipment

I wonder if this is best served by the macro bar, to keep the character sheet nice and tidy

> Show Mercurial effect and manifestation when spells are rolled

I think this should be optional to not clutter up the chat window

**Comment by mummson** [comment]
> Do you mean change the ability modifier, aside from what the ability score should make the modifier? I.e. give someone with a 10 Personality a +3 modifier?

Yes, it would be mainly used for luck, I have had players go to 20 and given them a +4 modifier. it's mainly a nice to have feature.
 
> I wonder if this is best served by the macro bar, to keep the character sheet nice and tidy

That is one way of doing it, but it can be cumbersome if the players have a few characters that they are playing in each campaign.

> I think this should be optional to not clutter up the chat window

Absolutely! IMHO I think all of my ideas should be optional :) the more I can customize the better :)

**Comment by mooped** [comment]
> I've been using this module for quite some time (almost 1 year!) and there are somethings that I'd really like to see added/improved to the otherwise amazing implementation of DCC to foundry ;)

Thanks, we appreciate the feedback.

> Here is my list in no particular order:
> 
>     * Allow Ability modifiers to be overwritten/modified manually

I need to think about how to make this work cleanly, but I'm definitely open to it.

> 
>     * Have a "favorite" option for weapons, skills, spells and or items/equipment
> 
>     * * And have them shown on the "Character" tab on the character sheet.

Tim has been working on a sheet rework for a while and it will happen eventually after a lot of refactoring. I'll probably hold off on this until that comes through as it may solve these problems anyway.

I quite like OSE's party sheet, and I'm tempted to implement something similar, but with clickable buttons (no promises yet though). I think this would solve a lot of problems people have running funnels and might also be a good place for the 'favourite' weapon to show up.

![image](https://user-images.githubusercontent.com/371357/129442828-b6a19b14-9f10-4ae9-a6d0-db71e46e3dce.png)

We're definitely interested in your thoughts on this.

>     * If the PC has more than one action die additional die buttons in front of weapons for each action die

We considered this, the downside is it could get unweildy with the baskstab button in there too.

In v0.30.0 we have a Roll Modifier system (Ctrl+Click any rollable and the dialog pops up so you can modify the formula before the roll is made). This gets customised for each type of roll. Spell checks and ability/skill checks get a checkPenalty UI with an appropriate default (it defaults to on for wizard/elf spells and off with a checkbox to enable it situationally for the other cases).

I've tried to cover all the options with it, but one thing we could do is include buttons for each Action Die in addition to the +/-1D buttons it currently has.

Do you think this would solve your action die problem well enough that the extra buttons wouldn't be necessary on the sheet?

![image](https://user-images.githubusercontent.com/371357/129442604-0bd3c3ff-b314-4235-be22-0df83701f064.png)
 
>     * Show Mercurial effect and manifestation when spells are rolled

This is on our roadmap.

>     * Don't show html tags in names of items/weapons
> 
>     * * Then you have the option to add flair to each item by adding html tags to names for bold, italic or what ever.

I'll definitely think about this. Might be a simple change but I need to see if there are knock on effects. The names are also the name Foundry uses for the item so I'd need to check if that causes a problem in the core Foundry UI.

>     * Allow for some way to call on ability modifiers with rolls both for skills/weapons and custom rolls "+@AGILMOD" for agility or something along those lines.

This will be in as part of v0.30.0. As you can see in the screenshot above it also pulls them out and labels them in the Roll Modifier dialog.

**Comment by mummson** [comment]
> > ```
> > * Allow Ability modifiers to be overwritten/modified manually
> > ```
> 
> I need to think about how to make this work cleanly, but I'm definitely open to it.
> 

To add to this, I don't let my PC's luck modifier change when they burn luck. having the ability to modify modifiers would make my life easyer :D 

> > ```
> > * Have a "favorite" option for weapons, skills, spells and or items/equipment
> > 
> > * * And have them shown on the "Character" tab on the character sheet.
> > ```
> 
> Tim has been working on a sheet rework for a while and it will happen eventually after a lot of refactoring. I'll probably hold off on this until that comes through as it may solve these problems anyway.
> 
> I quite like OSE's party sheet, and I'm tempted to implement something similar, but with clickable buttons (no promises yet though). I think this would solve a lot of problems people have running funnels and might also be a good place for the 'favourite' weapon to show up.
> 
> ![image](https://user-images.githubusercontent.com/371357/129442828-b6a19b14-9f10-4ae9-a6d0-db71e46e3dce.png)
> 
> We're definitely interested in your thoughts on this.
> 

This looks pretty cool. I'll have to test out the OSE system to see how this works. But from that sceenshot it looks very useful.

> > ```
> > * If the PC has more than one action die additional die buttons in front of weapons for each action die
> > ```
> 
> We considered this, the downside is it could get unweildy with the baskstab button in there too.
> 
> In v0.30.0 we have a Roll Modifier system (Ctrl+Click any rollable and the dialog pops up so you can modify the formula before the roll is made). This gets customised for each type of roll. Spell checks and ability/skill checks get a checkPenalty UI with an appropriate default (it defaults to on for wizard/elf spells and off with a checkbox to enable it situationally for the other cases).
> 
> I've tried to cover all the options with it, but one thing we could do is include buttons for each Action Die in addition to the +/-1D buttons it currently has.
> 
> Do you think this would solve your action die problem well enough that the extra buttons wouldn't be necessary on the sheet?
> 
> ![image](https://user-images.githubusercontent.com/371357/129442604-0bd3c3ff-b314-4235-be22-0df83701f064.png)
> 

This looks like a pretty good solution, I can see how having too many icons infront of each weapon would be too much. Only thing I'd like to see added to this would be character level, that is having the option to add levels to custom rolls. I guess you can do that as is with the + modifier.

> > ```
> > * Show Mercurial effect and manifestation when spells are rolled
> > ```
> 
> This is on our roadmap.
> 

Yeah, noticed that after I posted my list :)

> > ```
> > * Don't show html tags in names of items/weapons
> > 
> > * * Then you have the option to add flair to each item by adding html tags to names for bold, italic or what ever.
> > ```
> 
> I'll definitely think about this. Might be a simple change but I need to see if there are knock on effects. The names are also the name Foundry uses for the item so I'd need to check if that causes a problem in the core Foundry UI.
> 

Ahh I didn't think of that, but I think being able to put some flavor with html headings or something similar would be a nice touch.

> > ```
> > * Allow for some way to call on ability modifiers with rolls both for skills/weapons and custom rolls "+@AGILMOD" for agility or something along those lines.
> > ```
> 
> This will be in as part of v0.30.0. As you can see in the screenshot above it also pulls them out and labels them in the Roll Modifier dialog.

This all looks and sounds great!

**Comment by mooped** [comment]
I'm closing this, but I've crated issues for the outstanding bits and linked them back to this issue.
