### ISSUE TITLE
Elves shouldn't add luck to the Mecurial Table roll

### ISSUE THREAD

**Issue by vittordrow** [foundryvtt-dcc/dcc#273]
Per title, right now it gets affected by luck and that's a wizards only feature.

**Comment by mooped** [comment]
The rules are a bit ambiguous on this, but this doesn't match my interpretation.

You're correct that the Wizard class section explicitly calls out that luck applies to mercurial effects whereas the Elf class section does not mention mercurial effects.

However, the Elf class section says "Elves can cast spells as wizards do." which implies that all casting abilities (including the way that mercurial magic is generated) is carried over from the Wizard class.

To further reinforce this, the Mercurial Magic section on page 110 says when a Wizard learns a new spell they roll, on table 5-2 and add 10% x their luck modifier. There is no mention of Elves and no alternate mechanism called out for them. Without the clause in the Elf section saying that they cast as Wizards do you could come to the conclusion that Elves don't get mercurial effects at all, but with that section the conclusion is that Elves and Wizards generate their mercurial effects in the same way.
