### ISSUE TITLE
Roll Modifier dialog should include UI for spellburn

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/dcc#284]
Allow increasing or decreasing a modifier based on the relevant stats.
Track and limit stat spending appropriately.
Apply the stat changes to the character once the roll is made.

**Comment by industrialstr** [comment]
Actually, this is pretty important IMHO. I don't need it to automatically deduct stats or anything, just allow for a Spellburn option at casting time. I think the Judge and player should be able to work out the burn stats and limits ahead of time without much fuss - but it'd be nice to see the outcome modified by burn.

**Comment by mooped** [comment]
Please bear in mind you can already do what you're suggesting. One way is to Ctrl+Click the button when rolling the spell. The Roll Modifier dialog will give you the opportunity to modify the roll to account for spellburn by adjusting one of the existing modifiers. Alternatively you can use the buttons left of the spell check result in chat (if it was rolled through a spell item with a table) to adjust the check after the fact.

![image](https://user-images.githubusercontent.com/371357/132952992-9265a7c4-51c1-4d4e-b2db-c035ce5181c8.png)

![image](https://user-images.githubusercontent.com/371357/132953083-a346ca9b-9874-4c95-85cc-fe652c13c8ba.png)

This task is to provide a fully fledged UI as part of the Roll Modifier that shows the scores for the burnable stats, and allows the player to adjust them down to increase the roll without taking them below zero.

**Comment by industrialstr** [comment]
Yeah - that works a treat  - didn't notice that before. I have only just bought Foundry this week and downloaded the module for DCC so I am a complete noob.
I'd love to get into the guts and tinker as well eventually (being a coder myself) but time is always my foe.
Thanks!
Will

    On Saturday, September 11, 2021, 10:31:29 AM CDT, Steve Barnett ***@***.***> wrote:  
 
 


Please bear in mind you can already do what you're suggesting. One way is to Ctrl+Click the button when rolling the spell. The Roll Modifier dialog will give you the opportunity to modify the roll to account for spellburn by adjusting one of the existing modifiers. Alternatively you can use the buttons left of the spell check result in chat (if it was rolled through a spell item with a table) to adjust the check after the fact.





This task is to provide a fully fledged UI as part of the Roll Modifier that shows the scores for the burnable stats, and allows the player to adjust them down to increase the roll without taking them below zero.

**Comment by mooped** [comment]
Implemented in the v0.31.0 dev branch.
