### ISSUE TITLE
Provide a mechnism to help Legacy judges quickly setup mercurial effects

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/dcc#304]
See #235

> Feature/Function Request 1: Allow Mercurial Effects to be entered as items from a compendium.
> Benefit: This will benefit Legacy Judge's in preparation of games for players coming from other systems of play, and cut down prep time for the Wizard and Elf classes.

I'll have a think about the best way to do this. Currently we support assigning from the number but I know you mentioned this doesn't always help if people don't keep their legacy sheets well. Maybe it can just be a dropdown on the spell sheet if the Core Book is loaded, but I need to think about how it would fit in the UI.

**Comment by cyface** [comment]
I think this is covered by our Roll Mercurial Lookup now.
