### ISSUE TITLE
Fumbles and Luck

### ISSUE THREAD

**Issue by industrialstr** [foundryvtt-dcc/dcc#307]
I'm new to this mod and Foundry but the Fumble rolls appear to not be using the reverse of your luck score. For example, my less-than-lucky wizard with an 8 Luck (-1) rolls a 1d4 on the Fumble table and he should also apply +1 for the reverse of his luck (higher is worse on Fumbles). Instead, he is getting 1d4-1, which means he always is 1 value better than he should be. 

So his range of bad outcomes should be 2-5, not 0-3. This is actually pretty relevant.

Thanks!

**Comment by mooped** [comment]
Thanks for spotting this. It's down to some unintended side effects of our recent general improvements to dice rolling.

We'll get it sorted for the next release.

**Comment by industrialstr** [comment]
Cool - thanks mate!
    On Saturday, September 11, 2021, 10:26:38 AM CDT, Steve Barnett ***@***.***> wrote:  
 
 


Thanks for spotting this. It's down to some unintended side effects of our recent general improvements to dice rolling.

We'll get it sorted for the next release.
