### ISSUE TITLE
Automated attack bonus value doesn't work

### ISSUE THREAD

**Issue by Drevarte** [foundryvtt-dcc/dcc#321]
When I try inputting @ab into to hit slot it doesn't get the attack bonus value

**Comment by mooped** [comment]
@Drevarte I can't reproduce this on the current version of the system.

Would you mind confirming what version of the system you're running and if possible export the character you're seeing this on as JSON (right click them in the Actor directory) and attach that file so I can see the setup?

**Comment by mooped** [comment]
@Drevarte Ok, I've reproduced this and it's down to the default attack bonus mode being an invalid option. We'll get it fixed for the next release.

As a workaround for now you can open the Config dialog for the character, change the Attack Bonus mode to anything other than 'Flat' then set it back to 'Flat'.

**Comment by mooped** [comment]
Fixed for 0.32.0.
