### ISSUE TITLE
Add item ID to chat cards to aid Automated Animations integration 

### ISSUE THREAD

**Issue by justinthejaguar** [foundryvtt-dcc/dcc#329]
I made a request to Otigon to see if AA would work in DCC, but it looks like there is a hurdle with no determining to hit in the system atm. I thought I would forward Otigon’s reasoning. I know the feature is on your to-do.

https://github.com/otigon/automated-jb2a-animations/issues/298#issuecomment-1002697338

**Comment by mooped** [comment]
We should check this works with Maestro also.

**Comment by mooped** [comment]
Their comments also suggest that they only tried the default chat cards mode, they will also need to detect the individual to hit, damage, crit/fumble cards that can be enabled, and will likely become more common if we implement a way to separate these out into separately triggered rolls.
