### ISSUE TITLE
Inline notes field for equipment / ammunition.

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/dcc#338]
It would be helpful to be able to see/edit notes on equipment items on the equipment tab as we do for weapons/armor.

![image](https://user-images.githubusercontent.com/371357/153473301-be51ae61-d779-4337-95e2-c5761530e53b.png)

**Comment by monkey-bars** [comment]
It would also be great to have the notes for weapons listed in the chat card when an attack is rolled, for example.
