### ISSUE TITLE
Plain text import fails when no Weapon:

### ISSUE THREAD

**Issue by mphagan** [foundryvtt-dcc/dcc#340]
Purple Sorcerer update the L0 generator to activate the "no" filters.  No items or no funds imports, but no weapons fails.  If "Weapons:" is missing from the text during import, a "Failed to read player character (expecting Purple Sorcerer Plain Text or JSON)" message is displayed.  There are several adventures that start with PC having no weapons, hoping this is an easy fix.

If the "Weapon: Dagger -1 (1d4-1)" is changed to just "Weapon: ", it imports with no weapon.  But if the line is removed completely, the import fails with error. 

I could be way off on the cause/solution, but it is just missing an if statement on weaponString between line 336 and 337 in pc-parser.js, to account for the failed match?  
```
  const weaponString = pcString.match(/Weapon:\s+(.*)[;\n$]/)
  if (weaponString) {
    const weapon = weaponString.length > 0 ? _parseWeapon(weaponString[1]) : null
    if (weapon) {
      pcObject.weapon = weapon.name
      pcObject.attackMod = weapon.attackMod
      pcObject.attackDamage = weapon.attackDamage
    }
  }
```

**Comment by jdorety** [comment]
Fix submitted #386
