### ISSUE TITLE
Fleeting Luck Dialog doesn't resize after toggling filter

### ISSUE THREAD

**Issue by adotor** [foundryvtt-dcc/dcc#353]
Foundry: v9.269
DCC: 0.33.4
Browser: Edge (101.0.1210.47)

After toggling the fleeting luck filter for other players the dialog doesn't resize (closing and opening it via the sidebar is a workaround).

![image](https://user-images.githubusercontent.com/7715059/168774711-d5ca3559-73a8-4f0d-918b-59889bf8cd1c.png)

**Comment by cyface** [comment]
@adotor Hi! I just tested this to see if it needed a fix, and it seems to be working for me on system version 0.43.0 under Foundry Version 12.  Would you mind confirming if this is still not working for you? Thank you!

**Comment by adotor** [comment]
Hi @cyface,

the issue is no more (Foundry 12 Build 330, dcc 0.45.0).

You're welcome.
