### ISSUE TITLE
Automatically add ability modifiers to weapon rolls

### ISSUE THREAD

**Issue by monkey-bars** [foundryvtt-dcc/dcc#354]
When a PC has, for example, a +1 bonus to STR, this should be added to melee attack and damage roll automatically. Right now, you have to add the ability mod bonus to the "To Hit" and "Damage" rolls. Those spaces should be modifiers that come from the weapons themselves.

**Comment by algnc** [comment]
This should be a sheet level option, or per weapon, so we don't get tons of questions about how bonuses are calculated

**Comment by mooped** [comment]
The recent pull request we merged has added this as a global option.
