### ISSUE TITLE
Add field for birth luck modifier, with alias, to allow reference in the lucky roll

### ISSUE THREAD

**Issue by rbevers** [foundryvtt-dcc/dcc#359]
If there were a field where one could input the original Luck modifier for a character, it could be referenced in the right place to auto-apply it to a lucky roll.

----

E.g. I have a Butcher with a Cleaver (as axe) and an OG Luck of 16 (+2). My Judge rules it can be thrown like a handaxe. The butcher's birth augur is "Hawkeye" and lucky roll is Missile fire damage rolls.

#### BEFORE

Ranged Weapons...

Name: Cleaver (as axe, thrown)
To Hit: `@ab+@agi`
Damage: `1d6+2`

#### AFTER

Birth luck modifier: [+2]
Referenceable as `data.abilities.luck.birth.mod`
Alias as `@birthluck`.

Then in my character's Ranged Weapons I can put...

Name: Cleaver (as axe, thrown)
To Hit: `@ab+@agi`
Damage: `1d6+@birthluck`

And after my butcher has burned off 7 points of luck in his funnel, his lucky roll still behaves properly. I also don't later look at that `+2` and ask myself... "what was that for?" because I didn't bother to read my note about "Birth augur and lucky roll - Hawkeye: Missile fire damage roll" on a different tab.

#### Other thoughts...

Probably even nicer would be the ability to record birth Luck score and have the modifier auto-calculated. But let's not get greedy, eh?

**Comment by rbevers** [comment]
I do understand code, but of course this code is new to me. This looks like the place making the aliases... https://github.com/foundryvtt-dcc/dcc/blob/a64b9423c72e65c6db98956ada4bf87fa7b07c43/module/actor.js#L160-L195

Would y'all welcome a PR from a total unknown if I manage to write this myself? Any hints on the proper design before I make a butchery of it?

**Comment by mooped** [comment]
That'd be great, so long as it merges cleanly and passes the unit tests.

Ideally you'd modify the code linked below adding a second line that calculates a modifier from the max ability, so the alias just needs to look up that new field.

https://github.com/foundryvtt-dcc/dcc/blob/a64b9423c72e65c6db98956ada4bf87fa7b07c43/module/actor.js#L15
