### ISSUE TITLE
Having issue with rolling ability checks on zero level character tokens

### ISSUE THREAD

**Issue by akamoonknight** [foundryvtt-dcc/dcc#360]
When moving an Actor into a scene as a token, rolling ability checks seems to lose the base die and only 'rolls' the modifier.

https://github.com/foundryvtt-dcc/dcc/blob/a64b9423c72e65c6db98956ada4bf87fa7b07c43/templates/actor-sheet-zero-level.html#L41

I think this line is missing a ```system.``` in front of the final ```attributes.actionDice```.
Seemed to fix the issue I'm seeing at least, but I admittedly know nothing about this, so was just a guess.

**Comment by mooped** [comment]
Thanks for digging into it, that would definitely explain that regression along with a couple of other issues we've spotted.

**Comment by akamoonknight** [comment]
Awesome, thanks!
