### ISSUE TITLE
Use spells from compendium when importing actor

### ISSUE THREAD

**Issue by basic-element** [foundryvtt-dcc/dcc#365]
Right now, when you import stat block from purple sorcerer, it adds the spells for wizards and clerics but they are not the entries from the premium compendium with the spell results. It would be nice for the import process to use the spells from the compendium.

**Comment by mooped** [comment]
I had another go at this (I had an implementation a few years ago, but for whatever reason Foundry internals fell apart when trying to lookup packs during import - seems fine on V11 fortunately) and it's working with one caveats.

Purple Sorcerer's names don't exactly match our names, but so catches most but not all items and spells. Lots of the level 0 trade goods have odd names too, but they are either self explanatory or have the stats baked in so it's less of a problem.

**Comment by mooped** [comment]
Committed on dev-v0.40.0
We handle all types of item and all the edge cases I could find (I'm sure there will be more when people start using it).
