### ISSUE TITLE
Dice so Nice - Fleeting luck, disapproval, and lost spell messages do not wait for 3d dice to finish rolling

### ISSUE THREAD

**Issue by kerbsy** [foundryvtt-dcc/dcc#378]
The core DCC chat cards properly support Dice so Nice when the "Display chat message immediately" setting is unchecked. However, the messages created when disapproval increases, a wizard/elf spell is lost, or fleeting luck is generated/lost _do not_ respect this setting and are immediately sent to chat. The following video shows this bug in action with cleric disapproval.

https://user-images.githubusercontent.com/66316965/224864826-258f4af0-6b39-423f-9a3c-4f795c5ad088.mp4

**Comment by cyface** [comment]
@kerbsy I believe this is fixed in the just-released version 0.39.0
