### ISSUE TITLE
Add skill tab to Level zero sheets

### ISSUE THREAD

**Issue by crimsontree** [foundryvtt-dcc/dcc#384]
Unable to add the Skills tab to the zero level sheets.

**Comment by cyface** [comment]
@crimsontree as far as I know, zeros shouldn't have/need custom skills, so I'm trying to decide whether we should just hide that checkbox from the config tab, rather than enabling showing a custom skills tab at all for zero-level characters?

**Comment by cyface** [comment]
Fixed in 0.39.1
