### ISSUE TITLE
Divine Aid Disapproval Bug

### ISSUE THREAD

**Issue by LtDerek** [foundryvtt-dcc/dcc#385]
In one of the recent updates Divine Aid was changed to increase disapproval by 10 when used. 

_line 149 of template.json_
            "drainDisapproval": 10

However, this increase in disapproval triggers BEFORE you roll your Divine Aid check, meaning that you are very likely to fail the check.

This is not how the ability works in the Core Rule Book:

"This extraordinary act imparts a cumulative +10 penalty to **future** disapproval range"

**Comment by mooped** [comment]
Thanks for spotting this. Looks like a missing await when we call the special case logic for spell-like abilities (here https://github.com/foundryvtt-dcc/dcc/blob/e1e9e733ea21e0d3beca97535ee21a95ae25379b/module/actor.js#L588C41-L588C41).

**Comment by cyface** [comment]
This is fixed in 0.38.0
