### ISSUE TITLE
Fix and add tests for statblock that fails to import

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/dcc#400]
Wych-harpies (8): Init +3; Atk talons +1 melee (1 point); AC 12; HD 2d8; hp 15, 6, 12, 9, 10, 7, 15, 9; MV flight 30'; Act 1d20; SP snatch and grab; SV Fort +1, Ref +2, Will +2;

**Comment by cyface** [comment]
So this is failing because there is no alignment on the end.  Works fine with the alignment on the end.  Given the trailing semi-colon, it seems like it might have been missed in the copy/paste?

**Comment by cyface** [comment]
Works if original statblock is pasted in in its entirety.
