### ISSUE TITLE
Disapproval not automatically increasing on the sheet

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#404]
On spell results that generate disapproval, the range is not automatically increased on the sheet.

![image](https://github.com/foundryvtt-dcc/dcc/assets/7275595/190da376-4eb6-4579-8017-1339b9fc161f)

**Comment by mooped** [comment]
Fixed by https://github.com/foundryvtt-dcc/dcc/commit/8d5bb5bb79cd7f176e33f56953b47d075059b707
