### ISSUE TITLE
Selecting token and clicking INIT on sheet gives error "no token selected for rolling initiative!"

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#405]
When I select a token and click Init on their sheet to add them to initiative. 

![image](https://github.com/foundryvtt-dcc/dcc/assets/7275595/8bc052cb-033a-4bd8-b64f-bdbb1db3a034)

**Comment by mooped** [comment]
This happens when the token has not been added to the combat tracker.
