### ISSUE TITLE
Deed rolls seem to be rolling incorrectly - roll a 1 and a 6 shows in "Deed Roll". Roll a 4 and a 2 shows in "Deed Roll"

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#406]
Deed roll ends up blank
![image](https://github.com/foundryvtt-dcc/dcc/assets/7275595/8f815e3e-e6ca-4843-9fdd-1aeca69f35d7)

Deed roll shows wrong number
![image](https://github.com/foundryvtt-dcc/dcc/assets/7275595/aa052a33-85dc-4a35-884d-54f6628ccaac)

**Comment by mooped** [comment]
Fixed by https://github.com/foundryvtt-dcc/dcc/commit/8d5bb5bb79cd7f176e33f56953b47d075059b707
