### ISSUE TITLE
Foundry v12 import actors not working

### ISSUE THREAD

**Issue by CrownBerry** [foundryvtt-dcc/dcc#412]
Versions

FoundryVTT: v12.328
DCC: v0.42.0

Description:

I try to import actors, but receive this error
<img width="1210" alt="image" src="https://github.com/foundryvtt-dcc/dcc/assets/8062502/9d09c22b-a609-4e5b-86b4-3817d7dcf154">

**Comment by cyface** [comment]
Thanks for your report! I am going to push out a fix for the deprecation warning, but I don't think that was the actual source of the issue. 🤔  Once I push that fix out, please give it a try again, and post the purple sorcerer text you are using if you still have the issue.

**Comment by CrownBerry** [comment]
Hello.
I tested it on v0.43.0, but the problem still exists. I disabled all modules, including dcc-qol and dcc-core-compendium. The error looks the same:
<img width="1440" alt="image" src="https://github.com/foundryvtt-dcc/dcc/assets/8062502/35e5ab2c-d4f2-4686-9613-59878b13f1b9">

This time, I tried to import just one character; this is a plain text from Purple sorcerer:
```
Generator Settings
Source: Rulebook | Roll Mode: 3d6 | HP: normal | Augur: normal

0-level Occupation: Halfling mariner
Strength: 7 (-1)
Agility: 9 (0)
Stamina: 13 (+1)
Personality: 10 (0)
Intelligence: 7 (-1)
Luck: 6 (-1)

AC: 10; HP: 3
Weapon: Knife (as dagger) -1 (1d4-1)
Speed: 20; Init: 0; Ref: 0; Fort: 1; Will: 0

Equipment: Holy symbol (25 gp)
Trade good: Sailcloth (2 yards)
Starting Funds: 43 cp
Lucky sign: Seventh son (Spell checks) (-1)
Languages: English, Halfling
Racial Traits: Halfling ability: Infravision
```

**Comment by algnc** [comment]
It is working for me. Are you self hosted or on Forge?

**Comment by cyface** [comment]
Also you might try in a fresh world and see if that makes a difference.

**Comment by CrownBerry** [comment]
@algnc I host foundry on EC2 in AWS.

@cyface, this is a new empty world; I just started preparing for my first game in this system.
This world was migrated from foundry v11 to v12; this may be an issue. I'll try today to create a new world and test it there

**Comment by CrownBerry** [comment]
I tested this in an empty world without any scenes or modules.

Error the same:
<img width="1440" alt="image" src="https://github.com/foundryvtt-dcc/dcc/assets/8062502/0ae50253-22b5-483e-a752-1f271acd6350">

Plain text for import:
```
Generator Settings
Source: Rulebook | Roll Mode: 3d6 | HP: normal | Augur: toggle

0-level Occupation: Jester
Strength: 14 (+1)
Agility: 11 (0)
Stamina: 8 (-1)
Personality: 15 (+1)
Intelligence: 7 (-1)
Luck: 11 (0)

AC: 10; HP: 1
Weapon: Dart +0 (1d4+1)
Speed: 30; Init: 0; Ref: 0; Fort: -1; Will: 1

Equipment: Rope - 50' (25 cp)
Trade good: Silk clothes
Starting Funds: 29 cp
Lucky sign: Born under the loom (Skill checks, including thief)
Languages: Common

0-level Occupation: Soldier
Strength: 12 (0)
Agility: 10 (0)
Stamina: 5 (-2)
Personality: 10 (0)
Intelligence: 8 (-1)
Luck: 6 (-1)

AC: 11; HP: 1
Weapon: Spear +0 (1d8)
Speed: 30; Init: 0; Ref: -1; Fort: -2; Will: 0

Equipment: Waterskin (5 sp)
Trade good: Shield
Starting Funds: 37 cp
Lucky sign: Struck by lightning (Reflex saving throws) (-1)
Languages: Common

0-level Occupation: Dwarven mushroom-farmer
Strength: 9 (0)
Agility: 15 (+1)
Stamina: 15 (+1)
Personality: 8 (-1)
Intelligence: 13 (+1)
Luck: 8 (-1)

AC: 11; HP: 2
Weapon: Shovel (as staff) +0 (1d4)
Speed: 20; Init: 1; Ref: 1; Fort: 1; Will: -1

Equipment: Iron spike (1 sp)
Trade good: Sack
Starting Funds: 28 cp
Lucky sign: Survived the plague (Magical healing) (-1)
Languages: English, Dwarf, Gnome
Racial Traits: Dwarven ability: Infravision

0-level Occupation: Halfling haberdasher
Strength: 10 (0)
Agility: 10 (0)
Stamina: 11 (0)
Personality: 9 (0)
Intelligence: 11 (0)
Luck: 8 (-1)

AC: 10; HP: 1
Weapon: Scissors (as dagger) +0 (1d4)
Speed: 20; Init: 0; Ref: 0; Fort: 0; Will: -1

Equipment: Flint and steel (15 cp)
Trade good: Fine suits (3 sets)
Starting Funds: 19 cp
Lucky sign: Resisted temptation (Willpower saving throws) (-1)
Languages: English, Halfling
Racial Traits: Halfling ability: Infravision
``` 

Also, I tested it in few different browsers, but result is the same.

**Comment by cyface** [comment]
Can you try it locally?

**Comment by CrownBerry** [comment]
Yes, locally, it works with the same version of DCC and FoundryVTT.
Can I provide some additional information, maybe some logs?

**Comment by CrownBerry** [comment]
@cyface @algnc 
Oh, it works now, after I restarted the server in AWS. Strange, but OK. Anyway, thank's for your support!
