### ISSUE TITLE
Warrior crit range is cut off on new sheet

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#415]
It looks like Crit Range is cut off on the new Warrior sheet because the drop down is too small.

![image](https://github.com/user-attachments/assets/9454d096-feda-479b-b209-d929e56c390e)

**Comment by cyface** [comment]
I haven't worked on that tab yet. 👍🏻 I'll close this once I have.

**Comment by cyface** [comment]
@algnc should be fixed now.
