### ISSUE TITLE
NPC Statblock Import Failing since v12

### ISSUE THREAD

**Issue by wtripp64** [foundryvtt-dcc/dcc#422]
I was successful importing statblocks for NPCs from a PDF until I updated to v12.  Now I'm getting an error stating it failed to import because it was expecting a DCC statblock.  The statblocks are the same as they were before.

**Comment by cyface** [comment]
Could you please post the star locks you are trying to import? Often we see people leaving off the final period at the end. 🫡

**Comment by wtripp64** [comment]
This is one of the ones that failed

Gabbro (stone giant): Init +1; Atk club +18 melee (3d8+10)
or hurled stone +10 missile fire (1d8+10, range 200’); Crit
20-24 G/d4; AC 17; HD 12d10 (hp 72); MV 40’; Act 1d24; SP
infravision 60’, stone camouflage, transmute earth; SV Fort
+12, Ref +6, Will +8; AL N.

**Comment by wtripp64** [comment]
Just in case... this is another that failed:

Talus (cave bear): Init +2; Atk claw +4 melee (1d4) and bite
+5 melee (1d6+2); Crit M/d10; AC 17; HD 3d8 (hp 20); MV
20’, climb 10’; Act 2d20; SP charge; SV Fort +4, Ref +1, Will
+8; AL N.

**Comment by cyface** [comment]
Thanks! I am working on a fix!

**Comment by wtripp64** [comment]
Excellent!  Thank you so much!

**Comment by cyface** [comment]
Fixed in version 0.47.0 which is now the latest in Foundry.

**Comment by wtripp64** [comment]
Definitely fixed!  Thank you so much!  You've saved me a ton of time.

Wayne
