### ISSUE TITLE
dcc .50.0 beta 

### ISSUE THREAD

**Issue by Mumphry999** [foundryvtt-dcc/dcc#425]
I used the path to manifest and successfully installed and started a world with the new system, no problem there but when I went to the forge to check for updates on my installed systems and modules it prompted me to update to the old .47 dcc version

**Comment by cyface** [comment]
Yep! That is expected since the new version is still in beats and not officially released yet! Thanks for checking it out.

**Comment by Mumphry999** [comment]
Thanks for the quick response
