### ISSUE TITLE
New weapons always 1d3 damage

### ISSUE THREAD

**Issue by Locotomo** [foundryvtt-dcc/dcc#428]
All new weapons put on the sheet, are always 1d3 damage.

**Comment by cyface** [comment]
I believe I just fixed this if you can uninstall/reinstall.

**Comment by Locotomo** [comment]
No luck, or is there a new link?

**Comment by cyface** [comment]
Sorry about that, I have to build these beta release manually, and didn't do it correctly. Please do use the new link: https://github.com/foundryvtt-dcc/dcc/releases/download/v0.50.0-beta.2/system.json
