### ISSUE TITLE
Selecting 2x Mounted weapon damage rolls two damage dice

### ISSUE THREAD

**Issue by gabecook** [foundryvtt-dcc/dcc#449]
When selecting 2x Mounted weapon damage for a spear, two damage dice are rolled and each is multiplied by 2.

I believe it should be 2x the single 1d8.

![image](https://github.com/user-attachments/assets/e0ca4e85-644c-46e9-a1de-5900f52ace98)

**Comment by cyface** [comment]
Thanks for the report! I just pushed out a new version that should fix that.
