### ISSUE TITLE
Melee Damage with Negative Modifier Calculating Incorrectly

### ISSUE THREAD

**Issue by Regina-Hart** [foundryvtt-dcc/dcc#453]
If a Player or NPC has a negative melee damage modifier, the damage is not calculating correctly when rolled from the character sheet.

_Example_:  The actor has a -2 melee damage modifier.  He is using a weapon that does 1d6 damage.  When rolled from the character sheet, Foundry should roll 1d6 - 2.  For example, if the 1d6 result is 4, the calculated damage should be 2.  Instead, Foundry is rolling _max(1d6 - 2,1) + rolling max(1d6 - 2,1)_.

**Comment by cyface** [comment]
Thanks for the report! Looks like this works as desired for regular damage rolls, but not if automation is enabled. I will work on a fix!

**Comment by cyface** [comment]
Fixed in v0.50.17 !

**Comment by Regina-Hart** [comment]
Wow - that was a quick fix!  Thanks!
