### ISSUE TITLE
Actor Sheet - NPC : Armor Class Field is Read-Only

### ISSUE THREAD

**Issue by Regina-Hart** [foundryvtt-dcc/dcc#454]
The _Armor Class_ field on the NPC actor sheet is read-only.  It's possible to update it by switching the sheet to the Generic Sheet, making the edit, and switching back, but I suspect that's not the intended procedure!

<img width="448" alt="Actor NPC Sheet" src="https://github.com/user-attachments/assets/aae1314d-f30c-4a22-8d39-8ffda1c339c5">

**Comment by cyface** [comment]
Thanks for the report! Fixed in v0.50.18!

**Comment by Regina-Hart** [comment]
Holy Choranus!  Fixed in record time!
