### ISSUE TITLE
CSS Padding Missing from .dcc .character .languages label

### ISSUE THREAD

**Issue by Regina-Hart** [foundryvtt-dcc/dcc#455]
This is _incredibly_ minor, but DCC\styles\dcc.css is missing a line to add padding to the left of the 'Languages' label on the actor-partial-pc-common.html sheet.  (The 'Lucky Roll' label has this padding.)

**ADD**
.dcc .character .languages label {
   **padding-left: 3px;**
}

**Comment by cyface** [comment]
Fixed in v0.50.22
