### ISSUE TITLE
Equipment - Creating Items Wiki Link : Broken

### ISSUE THREAD

**Issue by Regina-Hart** [foundryvtt-dcc/dcc#457]
The **Equipment - Creating Items** [link](https://github.com/foundryvtt-dcc/dcc/wiki/Creating-Items) on the [Wiki](https://github.com/foundryvtt-dcc/dcc/wiki/FoundryVTT-DCC-System-User-Guide) returns you to the [Wiki home page](https://github.com/foundryvtt-dcc/dcc/wiki/).

**Comment by cyface** [comment]
Thanks, looks like no one ever wrote that article, so I just deleted it for now.
