### ISSUE TITLE
Roll Customizer Dialog - Triggered on Ctrl-Click or Right-Click

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#54]
It would be nice if rolls included some kind of framework for adding spellburn, luck, and for dice chain upgrades/downgrades.

Maybe any time a dice roll is made, it could prompt for that (optionally)

**Comment by cyface** [comment]
I would really prefer if it didn’t pop up any kind of message by default.  Rather, if you Ctrl-click, perhaps it could bring up and options dialog?

**Comment by algnc** [comment]
Yeah something that is optional would be fine. I don't like popups either

**Comment by mooped** [comment]
Ctrl + clicking sounds like a nice way to allow that without being too intrusive.

It would also be a good way to allow choosing an action dice at level 5 or above.

As part of this we should plumb the action die from the sheet into most of the rolls - currently they're hard coded to a d20.

**Comment by cyface** [comment]
This would also be used for linking to RollTables, and choosing a custom roll expression.

**Comment by mooped** [comment]
Let's start off with a simple dialog that allows editing the primary die and adding a straight modifier. This would cover most DCC situational modifiers and we can go further if there's demand for it.

We already have dice-chain.js which uses a temporary Foundry Roll object to determine the primary dice in a roll and give us its position in the dice chain for adjustments.
